# Generated by Django 3.2.16 on 2023-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
