# Generated by Django 3.2.16 on 2023-01-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ranking',
        ),
    ]
