# Generated by Django 3.2.16 on 2023-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sorting_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
