# Generated by Django 3.2.16 on 2023-01-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_sorting_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sorting_rating',
        ),
    ]
