# Generated by Django 3.2.16 on 2023-01-03 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('bad', 'Bad!'), ('average', 'Average!'), ('awesome', 'Awesome!')], default='average', max_length=50),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('profile', 'owner')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='five',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two',
        ),
    ]
