# Generated by Django 3.2.16 on 2023-01-16 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('rating', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='profile',
            new_name='profile_id',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('profile_id', 'owner')},
        ),
    ]
