# Generated by Django 3.2.16 on 2022-12-30 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following_user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed_user')},
        ),
    ]
